name: teste



on: 
  push: 
    branches:
      - main


jobs:
  pipeline:
      runs-on: self-hosted
      steps:
      - name: Checkout Repository      
        uses: actions/checkout@v2
      
      - name: Convair
        uses: actions/checkout@v2 # Git clone para dentro do Runner
        with:
          repository: trintoni/actions # Nome do repositorio que quero baixar
          path: ./.actions # Caminho onde quero que baixe

      - name: Define Branch Type
        uses: ./.actions/teste # "uses" Executa uma ação, no caso, o teste