name: teste



on: 
  push: 
    branches:
      - main
env:
  AKS_SECRET: ${{ secrets.AKS_SECRET }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  FUNCIONARIO: ${{ secrets.THIAGO }}
  FILE_DEPLOYMENT: deployment.yaml

jobs:
  pipeline:
      runs-on: self-hosted
      steps:
      - name: Checkout Repository      
        uses: actions/checkout@v2
      
      - name: Convair
        uses: actions/checkout@v2 # Git clone para dentro do Runner
        with:
          repository: trintoni/actions # Nome do repositorio que quero baixar
          path: ./.actions # Caminho onde quero que baixe

      - name: Define Branch Type
        uses: ./.actions/teste # "uses" Executa uma ação, no caso, o teste